name: "guide-to-vitebsk-server"

services:
  php:
    build: ./docker/php
    container_name: guide-to-vitebsk-server-php
    restart: unless-stopped
    volumes:
      - .:/var/www
  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: guide-to-vitebsk-server-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  postgres:
    image: postgres:16.3-alpine
    container_name: guide-to-vitebsk-server-postgres
    restart: unless-stopped
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: guide_to_vitebsk
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: guide_to_vitebsk
